language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer

services:
  - mysql

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  
before_script:
  - source ~/.nvm/nvm.sh
  - nvm install 6
  - bash travis/before-script.sh
  
script: php -d xdebug.profiler_enable=on -d xdebug.remote_enable=on -d xdebug.default_enable=on -d xdebug.remote_autostart=on -d xdebug.remote_host=localhost -d xdebug.remote_port=9000 vendor/phpunit/phpunit/phpunit --coverage-clover /tmp/coverage.xml
  
after_script:
  - bash travis/after-script.sh
