language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer

services:
  - mysql

addons:
  apt:
    packages:
      - nodejs

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - TRAVIS_NODE_VERSION="4"
  
before_script:
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - bash travis/before-script.sh

script: phpunit
  
after_script:
  - bash travis/after-script.sh
