language: php

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - nginx

php:
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  
before_script:
  - bash travis/before-script.sh

script: phpunit
